name: kanzza_sales_app_fe
description: "Kanzza Frozen Food mobile application."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^8.1.0
  flutter_map: ^8.3.0
  latlong2: ^0.9.1
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  http: ^1.6.0
  url_launcher: ^6.3.2
  fl_chart: ^0.68.0
  intl: ^0.19.0
  provider: ^6.1.1
  location: ^5.0.0
  path_provider: ^2.1.2
  permission_handler: ^11.0.1
  flutter_secure_storage: ^10.3.1
  webview_flutter: ^4.14.0
  image_picker: ^1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
